
FROM maven:3.9.3 AS builder
WORKDIR /chat-application
COPY . /chat-application/
RUN mvn clean package -DskipTests -e

# 2nd Docker build stage: copy builder output and configure entry point
FROM eclipse-temurin:17-jre
ENV APP_DIR /application
ENV APP_FILE chat-application-jar.jar

EXPOSE 8080

WORKDIR $APP_DIR
COPY --from=builder /chat-application/target/*.jar $APP_DIR/$APP_FILE

ENTRYPOINT ["sh", "-c","java $JAVA_OPTS -jar $APP_FILE"]